### ISSUE TITLE
clang-diagnostic-builtin-macro-redefined

### ISSUE THREAD

**Issue by HappyCerberus** [erenon/bazel_clang_tidy#29]
I run into a problem with this module when working on a talk about Bazel with C++.

Seems that clang-tidy doesn't respect `-Wno-builtin-macro-redefined` (see: https://github.com/llvm/llvm-project/issues/56709).

I managed to at least turn it from an error into a warning by changing the clang-tidy config to this:

```
UseColor: true

Checks: >
    bugprone-*,
    cppcoreguidelines-*,
    google-*,
    performance-*,
HeaderFilterRegex: ".*"

WarningsAsErrors: >
    bugprone-*,
    cppcoreguidelines-*,
    google-*,
    performance-*,
```

This was with:
```
Ubuntu LLVM version 16.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
```

**Comment by chenhao94** [comment]
Adding `--checks=-clang-diagnostic-builtin-macro-redefined` to clang-tidy options can suppress this warning.

**Comment by chenhao94** [comment]
I have a workaround by adding it to my own clang-tidy wrapper, but the best place to add it should be the [here](https://github.com/erenon/bazel_clang_tidy/blob/31d62bf825a94468b3d35c5ffd4e014e1c0ff566/clang_tidy/run_clang_tidy.sh)

**Comment by HappyCerberus** [comment]
Thanks this works.

**Comment by chandlerc** [comment]
Not sure why this was marked as completed, AFAICT the workaround described was not actually contributed?

Would it be OK for me to contribute a workaround? LLVM 16 is very widely used, and the relevant root cause (https://github.com/llvm/llvm-project/issues/61969) was never fixed in that release, and so until folks stop using the release this will be a problem for everyone who adopts this tool with C++20.
